### ISSUE TITLE
Feature Request - prioritize `op-batcher` and `op-proposer` next

### ISSUE THREAD

**Issue by sbvegan** [joohhnnn/Understanding-Optimism-Codebase#1]
From the questions I've gotten, there's a trend of folks looking to understand the rollup portion of the protocol first. My suggestion is to work on outlining the `op-batcher` and `op-proposer` sections next.

**Comment by joohhnnn** [comment]
already upload [op-batcher](https://github.com/joohhnnn/Understanding-Optimism-Codebase/blob/main/sequencer/03-how-batcher-works.md) and [op-proposer](https://github.com/joohhnnn/Understanding-Optimism-Codebase/blob/main/sequencer/05-how-proposer-works.md)

**Comment by sbvegan** [comment]
Thanks again for this! I got a ping from a developer this weekend and they let me know the resource was very helpful for them.

**Comment by joohhnnn** [comment]
I'm glad to hear that, it's quite encouraging for me as well :)
