### ISSUE TITLE
suggestion: links, commit versions 

### ISSUE THREAD

**Issue by aodhgan** [joohhnnn/Understanding-Optimism-Codebase#2]
This is dope! Would be useful to include hypertext links to the sections of code being walked thru too. And also the commit/version at which this was looked at, so it doesnt become obsolete when it inevitably changes/gets refactored. 

how is the progress on op-program?

**Comment by joohhnnn** [comment]
@aodhgan Thank you so much for your valuable feedback! I'll ensure to add the link and the commit version shortly.

Regarding the op-program, I have completed about 10% of the editing work and am still in the process of thoroughly researching and understanding how it actually functions. I've been quite occupied recently, but knowing that there's interest in the program is genuinely inspiring. This motivates me to return to it with renewed focus and accelerate its development. If you're interested in contributing, please don't hesitate to reach out. I would greatly appreciate your involvement and collaboration.

**Comment by joohhnnn** [comment]
@aodhgan Hi there, op-program and the whole fault proof system has already updated
